<script setup lang="ts">
import type { Component } from 'vue';
import {
  AtSign,
  ArrowDown,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  BadgeCheck,
  Bell,
  Blocks,
  Bold,
  BookOpen,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronsUpDown,
  CircleHelp,
  CircleX,
  Clipboard,
  Clock3,
  Compass,
  Copy,
  CreditCard,
  Eye,
  EyeOff,
  FileChartColumn,
  FilterX,
  FlaskConical,
  Grid2X2,
  Code,
  Heart,
  Heading2,
  Heading3,
  History,
  House,
  Image,
  Inbox,
  Info,
  Italic,
  KeyRound,
  Languages,
  LayoutDashboard,
  List,
  ListFilter,
  ListOrdered,
  LoaderCircle,
  LocateFixed,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  MemoryStick,
  MonitorCog,
  Network,
  Package,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  Paperclip,
  Pencil,
  Plus,
  Power,
  Quote,
  Redo2,
  RefreshCw,
  Route,
  Satellite,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Strikethrough,
  Sun,
  SunMoon,
  Terminal,
  Trash2,
  TriangleAlert,
  TrendingUp,
  Underline,
  Undo2,
  User,
  UserCog,
  UserPlus,
  Users,
  X,
  Zap,
} from '@lucide/vue';

const props = withDefaults(defineProps<{ name: string; size?: number; fill?: boolean }>(), {
  size: 20,
  fill: false,
});

// Icon choices preserve the meaning of the previous glyphs, rather than using
// Lucide as decoration. Interactive controls provide the accessible name; these
// SVGs remain decorative to avoid duplicate screen-reader announcements.
const ICONS: Record<string, Component> = {
  add: Plus,
  admin_panel_settings: ShieldCheck,
  alternate_email: AtSign,
  alt_route: Route,
  architecture: Network,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  attach_file: Paperclip,
  autorenew: RefreshCw,
  bolt: Zap,
  brightness_auto: SunMoon,
  cancel: CircleX,
  check: Check,
  check_circle: CheckCircle2,
  chevron_right: ChevronRight,
  close: X,
  code: Code,
  content_copy: Copy,
  copy_all: Clipboard,
  cottage: House,
  dark_mode: MonitorCog,
  delete: Trash2,
  done: Check,
  edit: Pencil,
  error: CircleX,
  expand_more: ChevronDown,
  favorite: Heart,
  favorite_border: Heart,
  filter_alt_off: FilterX,
  filter_list: ListFilter,
  format_bold: Bold,
  format_h2: Heading2,
  format_h3: Heading3,
  format_italic: Italic,
  format_list_bulleted: List,
  format_list_numbered: ListOrdered,
  format_quote: Quote,
  format_underlined: Underline,
  grid_view: Grid2X2,
  group: Users,
  history: History,
  home: House,
  hub: Network,
  image: Image,
  inbox: Inbox,
  info: Info,
  inventory_2: Package,
  key: KeyRound,
  keyboard_arrow_down: ChevronDown,
  left_panel_close: PanelLeftClose,
  left_panel_open: PanelLeftOpen,
  light_mode: Sun,
  login: LogIn,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  mark_email_read: MailCheck,
  memory: MemoryStick,
  menu_book: BookOpen,
  my_location: LocateFixed,
  notifications: Bell,
  palette: Palette,
  payments: CreditCard,
  person: User,
  person_add: UserPlus,
  photo_camera: Camera,
  power: Power,
  progress_activity: LoaderCircle,
  redo: Redo2,
  refresh: RefreshCw,
  satellite_alt: Satellite,
  schedule: Clock3,
  science: FlaskConical,
  search: Search,
  settings: Settings,
  shield: Shield,
  shopping_cart: ShoppingCart,
  space_dashboard: LayoutDashboard,
  strikethrough_s: Strikethrough,
  switch_account: UserCog,
  sync_alt: ArrowLeftRight,
  table_chart: FileChartColumn,
  terminal: Terminal,
  translate: Languages,
  travel_explore: Compass,
  trending_up: TrendingUp,
  undo: Undo2,
  unfold_more: ChevronsUpDown,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  view_list: List,
  visibility: Eye,
  visibility_off: EyeOff,
  warning: TriangleAlert,
  widgets: Blocks,
};

const icon = computed(() => ICONS[props.name] ?? CircleHelp);
</script>

<template>
  <component
    :is="icon"
    :size="size"
    :fill="fill ? 'currentColor' : 'none'"
    class="inline-block shrink-0"
    aria-hidden="true"
  />
</template>
