/**
 * `bun run init` — turn this starter kit into a new project.
 *
 * Renames every occurrence of the kit's identity (package scope `@nuxion/*`,
 * the `nuxion` slug used by compose project/container/volume names, the DB,
 * the buckets, the `.orb.local` domains, and the "Starter Kit" display name) to
 * yours, then writes a fresh `.env` with a generated JWT secret.
 *
 * The kit carries TWO frontend variants: `apps/web` (Nuxt, default) and
 * `apps/web-next` (Next.js). `--frontend` picks which one the new project
 * keeps; the other app plus its root references (compose services, env
 * section, scripts, docs blocks) are removed, and a Next pick additionally
 * moves `apps/web-next` into `apps/web` so every project has exactly one
 * frontend at the same path.
 *
 *   bun run init                                  # interactive
 *   bun run init --name portal-desa --yes         # non-interactive
 *   bun run init --name portal-desa --dry-run     # preview the changes only
 *   bun run init --frontend next --name my-app --yes --reset-git
 *
 * Flags:
 *   --name <slug>       kebab-case project slug (default: this directory's name)
 *   --display <name>    human-readable app name (default: Title Case of the slug)
 *   --frontend <v>      keep the Nuxt (default) or the Next frontend variant
 *   --yes, -y           accept defaults, skip prompts
 *   --dry-run           list the files that would change; write nothing
 *   --reset-git         delete .git and start a fresh history
 *   --force             run even with uncommitted changes
 */
import { execFileSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { existsSync, renameSync, rmSync } from 'node:fs';
import { readFile, rm, writeFile } from 'node:fs/promises';
import { basename, join } from 'node:path';
import { createInterface } from 'node:readline/promises';

const ROOT = join(import.meta.dir, '..');

// The kit's own identity, in the three casings that appear in the tree. Order
// matters: the scoped package prefix is replaced before the bare slug.
const KIT_SCOPE = '@nuxion/';
const KIT_SLUG = 'nuxion';
const KIT_DISPLAY = 'Nuxion';

// Files that must NOT be rewritten in place:
//   - this script (it contains the literals above — rewriting them mid-run would
//     corrupt it and make the rename non-repeatable)
//   - its spec, which asserts on those same literals
//   - the lockfile (regenerated by `bun install` once package names change)
const SKIP_FILES = new Set(['scripts/init-project.ts', 'scripts/init-project.spec.ts', 'bun.lock']);

const bold = (s: string) => `\x1b[1m${s}\x1b[0m`;
const dim = (s: string) => `\x1b[2m${s}\x1b[0m`;
const red = (s: string) => `\x1b[31m${s}\x1b[0m`;
const green = (s: string) => `\x1b[32m${s}\x1b[0m`;
const yellow = (s: string) => `\x1b[33m${s}\x1b[0m`;

export type FrontendVariant = 'nuxt' | 'next';

interface Options {
  name?: string;
  display?: string;
  frontend?: FrontendVariant;
  yes: boolean;
  dryRun: boolean;
  resetGit: boolean;
  force: boolean;
}

export function parseArgs(argv: string[]): Options {
  const opts: Options = { yes: false, dryRun: false, resetGit: false, force: false };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--yes' || arg === '-y') opts.yes = true;
    else if (arg === '--dry-run') opts.dryRun = true;
    else if (arg === '--reset-git') opts.resetGit = true;
    else if (arg === '--force') opts.force = true;
    else if (arg === '--name') opts.name = argv[++i];
    else if (arg.startsWith('--name=')) opts.name = arg.slice('--name='.length);
    else if (arg === '--display') opts.display = argv[++i];
    else if (arg.startsWith('--display=')) opts.display = arg.slice('--display='.length);
    else if (arg === '--frontend') opts.frontend = validateFrontendVariant(argv[++i] ?? '');
    else if (arg.startsWith('--frontend=')) {
      opts.frontend = validateFrontendVariant(arg.slice('--frontend='.length));
    } else throw new Error(`Unknown option: ${arg}`);
  }
  return opts;
}

export function validateFrontendVariant(value: string): FrontendVariant {
  if (value !== 'nuxt' && value !== 'next') {
    throw new Error(`Invalid frontend variant "${value}" — use "nuxt" or "next".`);
  }
  return value;
}

/**
 * A slug has to be legal everywhere it lands: an npm scope, a Docker Compose
 * project name, a container/volume name, a Postgres database name, and an S3
 * bucket name. Lowercase kebab-case satisfies all of them at once.
 */
export function validateSlug(slug: string): string {
  if (!/^[a-z][a-z0-9-]{1,38}$/.test(slug)) {
    throw new Error(
      `Invalid project name "${slug}". Use lowercase letters, digits and dashes, ` +
        'start with a letter, 2–39 characters (npm scope + Docker + Postgres + S3 safe).',
    );
  }
  if (slug.endsWith('-') || slug.includes('--')) {
    throw new Error(`Invalid project name "${slug}": no trailing or doubled dashes.`);
  }
  return slug;
}

/** `portal-desa` → `Portal Desa` — a reasonable default display name. */
export const titleCase = (slug: string): string =>
  slug
    .split('-')
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');

/** Apply the three renames to a blob of text. */
export function rename(content: string, slug: string, display: string): string {
  return content
    .split(KIT_SCOPE)
    .join(`@${slug}/`)
    .split(KIT_DISPLAY)
    .join(display)
    .split(KIT_SLUG)
    .join(slug);
}

// ── Frontend-variant surgery (pure string helpers) ─────────────────────────────

/** Drop every line that contains one of the needles. */
export function removeLinesContaining(content: string, needles: string[]): string {
  if (!needles.length) return content;
  return content
    .split('\n')
    .filter((line) => !needles.some((needle) => line.includes(needle)))
    .join('\n');
}

/**
 * Remove a compose service block: the `  <name>:` key line, the banner
 * comment lines glued directly above it, and every deeper-indented line
 * below — up to (exclusive) the next service key, the comment block that
 * belongs to it, or a top-level key. Assumes the kit's layout: block content
 * is indented 4+ and sibling services never carry indent-2 comments inside
 * their own bodies.
 */
export function removeServiceBlock(yaml: string, service: string): string {
  const lines = yaml.split('\n');
  const keyIndex = lines.findIndex((line) => line === `  ${service}:`);
  if (keyIndex === -1) return yaml;

  let start = keyIndex;
  while (start > 0 && /^ {2}#/.test(lines[start - 1]!)) start -= 1;

  let end = lines.length;
  for (let i = keyIndex + 1; i < lines.length; i++) {
    const line = lines[i]!;
    if (line.trim() === '' || /^ {4,}/.test(line)) continue;
    end = i; // first indent-0..2 key/comment after the block
    break;
  }
  while (end > keyIndex && lines[end - 1]?.trim() === '') end -= 1;

  lines.splice(start, end - start);
  return lines.join('\n').replace(/\n{3,}/g, '\n\n');
}

/** Remove a `# ── …` section (banner line through the next banner/box header). */
export function removeEnvSection(content: string, banner: string): string {
  const lines = content.split('\n');
  const start = lines.findIndex((line) => line.startsWith(banner));
  if (start === -1) return content;
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    if (/^# [─╭]/.test(lines[i]!)) {
      end = i;
      break;
    }
  }
  while (end > start && lines[end - 1]?.trim() === '') end -= 1;
  lines.splice(start, end - start);
  return lines.join('\n').replace(/\n{3,}/g, '\n\n');
}

/** Remove a `<!-- marker --> … <!-- /marker -->` documentation block. */
export function removeMarkedBlock(markdown: string, marker: string): string {
  const pattern = new RegExp(
    `<!--[\\s]*${marker}[\\s]*-->[\\s\\S]*?<!--[\\s]*/${marker}[\\s]*-->\\n?`,
  );
  return markdown.replace(pattern, '').replace(/\n{3,}/g, '\n\n');
}

/**
 * Remove the YAML list stanza containing the needle: the `  - ` item the
 * needle lives in, up to (exclusive) the next `  - ` sibling or a top-level
 * key. Used for dependabot entries.
 */
export function removeListEntry(content: string, needle: string): string {
  const lines = content.split('\n');
  const needleIndex = lines.findIndex((line) => line.includes(needle));
  if (needleIndex === -1) return content;
  let start = needleIndex;
  while (start > 0 && !/^ {2}- /.test(lines[start - 1]!)) start -= 1;
  start -= 1; // the list item line itself
  let end = lines.length;
  for (let i = needleIndex + 1; i < lines.length; i++) {
    if (/^ {2}- /.test(lines[i]!) || /^\S/.test(lines[i]!)) {
      end = i;
      break;
    }
  }
  while (end > needleIndex && lines[end - 1]?.trim() === '') end -= 1;
  lines.splice(start, end - start);
  return lines.join('\n').replace(/\n{3,}/g, '\n\n');
}

/** Sequential literal replacements (split/join, no regex escaping traps). */
export function replaceLiterals(content: string, pairs: Array<[string, string]>): string {
  return pairs.reduce((acc, [from, to]) => acc.split(from).join(to), content);
}

interface FileOps {
  removeServices?: string[];
  removeEnvSections?: string[];
  removeMarkers?: string[];
  removeListEntries?: string[];
  removeLines?: string[];
  replace?: Array<[string, string]>;
}

function applyFileOps(content: string, ops: FileOps): string {
  let out = content;
  for (const service of ops.removeServices ?? []) out = removeServiceBlock(out, service);
  for (const banner of ops.removeEnvSections ?? []) out = removeEnvSection(out, banner);
  for (const marker of ops.removeMarkers ?? []) out = removeMarkedBlock(out, marker);
  for (const needle of ops.removeListEntries ?? []) out = removeListEntry(out, needle);
  // Replacements run before line removals: a replacement can rescue a line
  // (e.g. re-point the ports-table row at the Next var) that a NUXT_ needle
  // would otherwise delete wholesale.
  out = replaceLiterals(out, ops.replace ?? []);
  out = removeLinesContaining(out, ops.removeLines ?? []);
  return out;
}

// What each variant removes from the root files. Both directions are
// idempotent: needles that no longer match simply leave the file untouched,
// so running against an older tree (or twice) is safe.
const NUXT_OPS: Record<string, FileOps> = {
  'docker-compose.yml': {
    removeServices: ['web-next'],
    removeLines: ['web-next', 'web_next_node_modules'],
  },
  'docker-compose.prod.yml': { removeServices: ['web-next'] },
  '.env.example': { removeEnvSections: ['# ── Web variant: Next'] },
  'README.md': {
    removeMarkers: ['web-variant:next'],
    replace: [
      [
        'A **Bun + Turbo monorepo** starter kit — NestJS API + a web frontend in two\nvariants (**Nuxt 4** by default, **Next.js 16** via `--frontend next`), with',
        'A **Bun + Turbo monorepo** starter kit — NestJS API + a **Nuxt 4** web frontend, with',
      ],
      ['Nuxt: `--dotenv ../../.env` · Next: dotenv-cli scripts', 'Nuxt: `--dotenv ../../.env`'],
    ],
    removeLines: [
      'web-next/',
      'WEB_NEXT_PORT',
      'serve:web-next',
      '--frontend next',
      'Frontend (variant)',
    ],
  },
  'package.json': { removeLines: ['"serve:web-next"'] },
  '.github/dependabot.yml': {
    removeListEntries: ["directory: '/apps/web-next'"],
    removeLines: ['next 17', 'react 20'],
  },
  'turbo.json': {
    replace: [
      [
        '"outputs": ["dist/**", ".output/**", ".nuxt/**", ".next/**", "!.next/cache/**"]',
        '"outputs": ["dist/**", ".output/**", ".nuxt/**"]',
      ],
    ],
  },
};

const NEXT_OPS: Record<string, FileOps> = {
  'docker-compose.yml': {
    removeServices: ['web'],
    replace: [['web (nuxt HMR)', 'web (next HMR)']],
    // The surviving web service loses its opt-in profile — it is now the
    // only frontend, so `docker compose up` must start it by default. The
    // stale Nuxt references go too (the nuxt web block is already gone).
    removeLines: [
      'profiles: [next]',
      '`next` profile',
      '--profile next up',
      'side by side',
      'container port 3000',
      'web_node_modules:',
      'NUXT_',
    ],
  },
  'docker-compose.prod.yml': {
    removeServices: ['web'],
    removeLines: ['profiles: [next]', '`next` profile', '--profile next up', 'side by side'],
  },
  '.env.example': {
    removeEnvSections: ['# ── Web variant: Nuxt'],
    replace: [['APP_URL=http://localhost:3000', 'APP_URL=http://localhost:8080']],
    removeLines: ['NUXT_', 'WEB_PORT=3000'],
  },
  'README.md': {
    removeMarkers: ['web-variant:nuxt'],
    replace: [
      [
        'A **Bun + Turbo monorepo** starter kit — NestJS API + a web frontend in two\nvariants (**Nuxt 4** by default, **Next.js 16** via `--frontend next`), with',
        'A **Bun + Turbo monorepo** starter kit — NestJS API + a **Next.js 16** web frontend, with',
      ],
      ['`NUXT_API_INTERNAL_BASE` / `NEXT_API_INTERNAL_BASE`', '`NEXT_API_INTERNAL_BASE`'],
      ['Frontend (variant) |', 'Frontend |'],
      ['Nuxt: `--dotenv ../../.env` · Next: dotenv-cli scripts', 'dotenv-cli scripts'],
    ],
    removeLines: [
      'Nuxt 4 (Vue 3) frontend',
      '· shadcn-vue (Reka UI)',
      '| Web (Nuxt)',
      '— Nuxt (`:3000`',
      'NUXT_',
    ],
  },
  'package.json': { removeLines: ['"serve:web": "turbo run dev --filter=@nuxion/web",'] },
  '.github/dependabot.yml': { removeListEntries: ["directory: '/apps/web'"] },
};

// After the structural ops, a Next pick re-points every remaining literal at
// the canonical `web` name so the moved app owns the default slot: package
// scope, compose service, scripts, docs. The pairs are disjoint strings
// (underscore volume vs hyphen names vs env casing), so ordering is cosmetic.
const NEXT_GLOBAL_REPLACEMENTS: Array<[string, string]> = [
  ['web_next_node_modules', 'web_node_modules'],
  ['WEB_NEXT_PORT', 'WEB_PORT'],
  ['WEB_PORT:-3000', 'WEB_PORT:-8080'],
  ['web-next', 'web'],
];

const git = (args: string[]): string =>
  execFileSync('git', args, { cwd: ROOT, encoding: 'utf-8' }).trim();

/**
 * Only git-tracked files are rewritten. That excludes node_modules, build output
 * and local `.env`s for free, and it means every change is reviewable with
 * `git diff` (and revertible with `git checkout .`).
 */
function trackedFiles(): string[] {
  return git(['ls-files'])
    .split('\n')
    .filter((file) => file && !SKIP_FILES.has(file));
}

/**
 * Keep only the chosen frontend variant. Runs AFTER the kit-identity guard
 * (never inside the kit itself) and BEFORE the identity rename, so the
 * rename sees the post-swap tree — including `apps/web-next` already moved
 * onto `apps/web`. The physical move is re-staged (`git add -A`) so the
 * rename's `git ls-files` reflects the new paths.
 */
async function applyFrontendVariant(variant: FrontendVariant, dryRun: boolean): Promise<string[]> {
  const ops = variant === 'next' ? NEXT_OPS : NUXT_OPS;

  if (!dryRun) {
    if (variant === 'next') {
      rmSync(join(ROOT, 'apps/web'), { recursive: true, force: true });
      rmSync(join(ROOT, 'docker/dev-web.sh'), { force: true });
      rmSync(join(ROOT, 'docker/prod-web.sh'), { force: true });
      renameSync(join(ROOT, 'apps/web-next'), join(ROOT, 'apps/web'));
      renameSync(join(ROOT, 'docker/dev-web-next.sh'), join(ROOT, 'docker/dev-web.sh'));
      renameSync(join(ROOT, 'docker/prod-web-next.sh'), join(ROOT, 'docker/prod-web.sh'));
      // Refresh the index so `git ls-files` lists the moved files at their
      // new paths (content edits alone don't need this; renames do).
      execFileSync('git', ['add', '-A'], { cwd: ROOT });
    } else {
      rmSync(join(ROOT, 'apps/web-next'), { recursive: true, force: true });
      rmSync(join(ROOT, 'docker/dev-web-next.sh'), { force: true });
      rmSync(join(ROOT, 'docker/prod-web-next.sh'), { force: true });
    }
  }

  const changed: string[] = [];
  for (const file of trackedFiles()) {
    const path = join(ROOT, file);
    let content: string;
    try {
      content = await readFile(path, 'utf-8');
    } catch {
      continue; // unreadable / deleted since `git ls-files` — nothing to rewrite
    }
    if (content.includes('\0')) continue; // binaries stay untouched

    let next = applyFileOps(content, ops[file] ?? {});
    if (variant === 'next') next = replaceLiterals(next, NEXT_GLOBAL_REPLACEMENTS);
    if (next === content) continue;

    changed.push(file);
    if (!dryRun) await writeFile(path, next);
  }
  return changed;
}

async function main(): Promise<void> {
  const opts = parseArgs(process.argv.slice(2));

  if (!opts.force && !opts.dryRun && git(['status', '--porcelain'])) {
    throw new Error(
      'Working tree has uncommitted changes. Commit or stash them first so the ' +
        'rename is easy to review and revert — or pass --force.',
    );
  }

  // ── 1. Gather the new identity ──────────────────────────────────────────────
  const defaultSlug = basename(ROOT)
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '');
  let slug = opts.name ?? defaultSlug;
  let display = opts.display ?? titleCase(slug);
  let frontend: FrontendVariant = opts.frontend ?? 'nuxt';

  if (!opts.yes && process.stdin.isTTY) {
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    try {
      console.log(bold('\nInit project dari starter kit\n'));
      slug = (await rl.question(`Nama project (slug) [${slug}]: `)).trim() || slug;
      validateSlug(slug);
      display =
        (await rl.question(`Nama tampilan [${titleCase(slug)}]: `)).trim() || titleCase(slug);
      const variantAnswer = (await rl.question(`Frontend variant [nuxt/next] (${frontend}): `))
        .trim()
        .toLowerCase();
      if (variantAnswer) frontend = validateFrontendVariant(variantAnswer);
    } finally {
      rl.close();
    }
  }
  validateSlug(slug);

  if (slug === KIT_SLUG) {
    console.log(yellow('Nama masih "nuxion" — tidak ada yang diubah.'));
    return;
  }

  // ── 2. Keep only the chosen frontend variant ────────────────────────────────
  // Before the identity rename so the moved/trimmed tree is what gets renamed;
  // after the slug guard so the kit itself is never swapped.
  const variantChanged = await applyFrontendVariant(frontend, opts.dryRun);
  if (opts.dryRun) {
    console.log(
      dim(`\nFrontend variant: ${frontend} — ${variantChanged.length} file akan disesuaikan.`),
    );
  } else if (variantChanged.length) {
    console.log(
      green(`✔ frontend variant "${frontend}" — ${variantChanged.length} file disesuaikan`),
    );
  }

  // ── 3. Rewrite tracked files ────────────────────────────────────────────────
  const changed: string[] = [];
  for (const file of trackedFiles()) {
    const path = join(ROOT, file);
    let content: string;
    try {
      content = await readFile(path, 'utf-8');
    } catch {
      continue; // unreadable / deleted since `git ls-files` — nothing to rename
    }
    // Skip binaries: a NUL byte means this isn't text we should be editing.
    if (content.includes('\0')) continue;

    const renamed = rename(content, slug, display);
    if (renamed === content) continue;
    changed.push(file);
    if (!opts.dryRun) await writeFile(path, renamed);
  }

  // ── 4. Seed .env ────────────────────────────────────────────────────────────
  const envPath = join(ROOT, '.env');
  const envExists = existsSync(envPath);
  if (!envExists && !opts.dryRun) {
    const example = await readFile(join(ROOT, '.env.example'), 'utf-8');
    // The example was rewritten in the steps above, so it already carries the
    // new slug and the chosen variant's env section.
    const env = example.replace(
      /^JWT_SECRET=.*$/m,
      `JWT_SECRET=${randomBytes(32).toString('base64url')}`,
    );
    await writeFile(envPath, env);
  }

  // ── 5. Report ───────────────────────────────────────────────────────────────
  if (opts.dryRun) {
    console.log(bold(`\nDry run — ${changed.length} file akan diubah:`));
    for (const file of changed) console.log(`  ${file}`);
    console.log(dim(`\n@nuxion/ → @${slug}/   nuxion → ${slug}   Nuxion → ${display}`));
    return;
  }

  if (opts.resetGit) {
    await rm(join(ROOT, '.git'), { recursive: true, force: true });
    execFileSync('git', ['init', '-q'], { cwd: ROOT });
  }

  console.log(green(`\n✔ ${changed.length} file diubah → ${bold(display)} (${slug})`));
  console.log(
    envExists
      ? yellow('! .env sudah ada dan TIDAK disentuh — samakan sendiri dengan .env.example.')
      : dim('  .env dibuat dari .env.example (JWT_SECRET digenerate).'),
  );
  console.log(`
${bold('Langkah berikutnya')}
  1. bun install                 ${dim('# regenerate bun.lock dengan nama paket baru')}
  2. docker compose up -d        ${dim(`# volume/container baru: ${slug}-postgres, dll.`)}
  3. bun run --filter @${slug}/api db:migrate
  4. bun run --filter @${slug}/api db:seed
${
  opts.resetGit
    ? dim('  (git history direset — commit pertama masih menunggu)')
    : dim('  Review dengan `git diff`; batalkan dengan `git checkout .`')
}
${yellow('Volume lama nuxion_* (milik kit) masih ada — hapus dengan: docker volume ls | grep nuxion')}
`);
}

// Guarded so the exported helpers can be imported by tests without renaming the repo.
if (import.meta.main) {
  main().catch((error: Error) => {
    console.error(red(`✖ ${error.message}`));
    process.exit(1);
  });
}
