/**
 * `bun run init` — turn this starter kit into a new project.
 *
 * Renames every occurrence of the kit's identity (package scope `@nuxion/*`,
 * the `nuxion` slug used by compose project/container/volume names, the DB,
 * the buckets, the `.orb.local` domains, and the "Starter Kit" display name) to
 * yours, then writes a fresh `.env` with a generated JWT secret.
 *
 *   bun run init                                  # interactive
 *   bun run init --name portal-desa --yes         # non-interactive
 *   bun run init --name portal-desa --dry-run     # preview the changes only
 *
 * Flags:
 *   --name <slug>       kebab-case project slug (default: this directory's name)
 *   --display <name>    human-readable app name (default: Title Case of the slug)
 *   --yes, -y           accept defaults, skip prompts
 *   --dry-run           list the files that would change; write nothing
 *   --reset-git         delete .git and start a fresh history
 *   --force             run even with uncommitted changes
 */
import { execFileSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { existsSync } from 'node:fs';
import { readFile, rm, writeFile } from 'node:fs/promises';
import { basename, join } from 'node:path';
import { createInterface } from 'node:readline/promises';

const ROOT = join(import.meta.dir, '..');

// The kit's own identity, in the three casings that appear in the tree. Order
// matters: the scoped package prefix is replaced before the bare slug.
const KIT_SCOPE = '@nuxion/';
const KIT_SLUG = 'nuxion';
const KIT_DISPLAY = 'Nuxion';

// Files that must NOT be rewritten in place:
//   - this script (it contains the literals above — rewriting them mid-run would
//     corrupt it and make the rename non-repeatable)
//   - its spec, which asserts on those same literals
//   - the lockfile (regenerated by `bun install` once package names change)
const SKIP_FILES = new Set(['scripts/init-project.ts', 'scripts/init-project.spec.ts', 'bun.lock']);

const bold = (s: string) => `\x1b[1m${s}\x1b[0m`;
const dim = (s: string) => `\x1b[2m${s}\x1b[0m`;
const red = (s: string) => `\x1b[31m${s}\x1b[0m`;
const green = (s: string) => `\x1b[32m${s}\x1b[0m`;
const yellow = (s: string) => `\x1b[33m${s}\x1b[0m`;

interface Options {
  name?: string;
  display?: string;
  yes: boolean;
  dryRun: boolean;
  resetGit: boolean;
  force: boolean;
}

export function parseArgs(argv: string[]): Options {
  const opts: Options = { yes: false, dryRun: false, resetGit: false, force: false };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--yes' || arg === '-y') opts.yes = true;
    else if (arg === '--dry-run') opts.dryRun = true;
    else if (arg === '--reset-git') opts.resetGit = true;
    else if (arg === '--force') opts.force = true;
    else if (arg === '--name') opts.name = argv[++i];
    else if (arg.startsWith('--name=')) opts.name = arg.slice('--name='.length);
    else if (arg === '--display') opts.display = argv[++i];
    else if (arg.startsWith('--display=')) opts.display = arg.slice('--display='.length);
    else throw new Error(`Unknown option: ${arg}`);
  }
  return opts;
}

/**
 * A slug has to be legal everywhere it lands: an npm scope, a Docker Compose
 * project name, a container/volume name, a Postgres database name, and an S3
 * bucket name. Lowercase kebab-case satisfies all of them at once.
 */
export function validateSlug(slug: string): string {
  if (!/^[a-z][a-z0-9-]{1,38}$/.test(slug)) {
    throw new Error(
      `Invalid project name "${slug}". Use lowercase letters, digits and dashes, ` +
        'start with a letter, 2–39 characters (npm scope + Docker + Postgres + S3 safe).',
    );
  }
  if (slug.endsWith('-') || slug.includes('--')) {
    throw new Error(`Invalid project name "${slug}": no trailing or doubled dashes.`);
  }
  return slug;
}

/** `portal-desa` → `Portal Desa` — a reasonable default display name. */
export const titleCase = (slug: string): string =>
  slug
    .split('-')
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');

/** Apply the three renames to a blob of text. */
export function rename(content: string, slug: string, display: string): string {
  return content
    .split(KIT_SCOPE)
    .join(`@${slug}/`)
    .split(KIT_DISPLAY)
    .join(display)
    .split(KIT_SLUG)
    .join(slug);
}

const git = (args: string[]): string =>
  execFileSync('git', args, { cwd: ROOT, encoding: 'utf8' }).trim();

/**
 * Only git-tracked files are rewritten. That excludes node_modules, build output
 * and local `.env`s for free, and it means every change is reviewable with
 * `git diff` (and revertible with `git checkout .`).
 */
function trackedFiles(): string[] {
  return git(['ls-files'])
    .split('\n')
    .filter((file) => file && !SKIP_FILES.has(file));
}

async function main(): Promise<void> {
  const opts = parseArgs(process.argv.slice(2));

  if (!opts.force && !opts.dryRun && git(['status', '--porcelain'])) {
    throw new Error(
      'Working tree has uncommitted changes. Commit or stash them first so the ' +
        'rename is easy to review and revert — or pass --force.',
    );
  }

  // ── 1. Gather the new identity ──────────────────────────────────────────────
  const defaultSlug = basename(ROOT)
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '');
  let slug = opts.name ?? defaultSlug;
  let display = opts.display ?? titleCase(slug);

  if (!opts.yes && process.stdin.isTTY) {
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    try {
      console.log(bold('\nInit project dari starter kit\n'));
      slug = (await rl.question(`Nama project (slug) [${slug}]: `)).trim() || slug;
      validateSlug(slug);
      display =
        (await rl.question(`Nama tampilan [${titleCase(slug)}]: `)).trim() || titleCase(slug);
    } finally {
      rl.close();
    }
  }
  validateSlug(slug);

  if (slug === KIT_SLUG) {
    console.log(yellow('Nama masih "nuxion" — tidak ada yang diubah.'));
    return;
  }

  // ── 2. Rewrite tracked files ────────────────────────────────────────────────
  const changed: string[] = [];
  for (const file of trackedFiles()) {
    const path = join(ROOT, file);
    let content: string;
    try {
      content = await readFile(path, 'utf8');
    } catch {
      continue; // unreadable / deleted since `git ls-files` — nothing to rename
    }
    // Skip binaries: a NUL byte means this isn't text we should be editing.
    if (content.includes('\0')) continue;

    const renamed = rename(content, slug, display);
    if (renamed === content) continue;
    changed.push(file);
    if (!opts.dryRun) await writeFile(path, renamed);
  }

  // ── 3. Seed .env ────────────────────────────────────────────────────────────
  const envPath = join(ROOT, '.env');
  const envExists = existsSync(envPath);
  if (!envExists && !opts.dryRun) {
    const example = await readFile(join(ROOT, '.env.example'), 'utf8');
    // The example was rewritten in step 2, so it already carries the new slug.
    const env = example.replace(
      /^JWT_SECRET=.*$/m,
      `JWT_SECRET=${randomBytes(32).toString('base64url')}`,
    );
    await writeFile(envPath, env);
  }

  // ── 4. Report ───────────────────────────────────────────────────────────────
  if (opts.dryRun) {
    console.log(bold(`\nDry run — ${changed.length} file akan diubah:`));
    for (const file of changed) console.log(`  ${file}`);
    console.log(dim(`\n@nuxion/ → @${slug}/   nuxion → ${slug}   Nuxion → ${display}`));
    return;
  }

  if (opts.resetGit) {
    await rm(join(ROOT, '.git'), { recursive: true, force: true });
    execFileSync('git', ['init', '-q'], { cwd: ROOT });
  }

  console.log(green(`\n✔ ${changed.length} file diubah → ${bold(display)} (${slug})`));
  console.log(
    envExists
      ? yellow('! .env sudah ada dan TIDAK disentuh — samakan sendiri dengan .env.example.')
      : dim('  .env dibuat dari .env.example (JWT_SECRET digenerate).'),
  );
  console.log(`
${bold('Langkah berikutnya')}
  1. bun install                 ${dim('# regenerate bun.lock dengan nama paket baru')}
  2. bun run --filter @${slug}/api prisma:generate  ${dim('# generated client masih menyimpan nama lama')}
  3. docker compose up -d        ${dim(`# volume/container baru: ${slug}-postgres, dll.`)}
  4. bun run --filter @${slug}/api prisma:migrate
  5. bun run --filter @${slug}/api db:seed
${
  opts.resetGit
    ? dim('  (git history direset — commit pertama masih menunggu)')
    : dim('  Review dengan `git diff`; batalkan dengan `git checkout .`')
}
${yellow('Volume lama nuxion_* (milik kit) masih ada — hapus dengan: docker volume ls | grep nuxion')}
`);
}

// Guarded so the exported helpers can be imported by tests without renaming the repo.
if (import.meta.main) {
  main().catch((error: Error) => {
    console.error(red(`✖ ${error.message}`));
    process.exit(1);
  });
}
